# Generated by Django 5.1.7 on 2025-03-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('escritorio', models.CharField(max_length=200)),
                ('codigo_zage', models.CharField(max_length=200)),
                ('codigo_assistente', models.CharField(max_length=200)),
                ('codigo_fornecedor', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('superior', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('tabela', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('pedido', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=200)),
                ('forma_pagamento', models.CharField(max_length=200)),
                ('condicao_pagamento', models.CharField(max_length=200)),
                ('vendedor', models.CharField(max_length=200)),
                ('escritorio', models.CharField(max_length=200)),
                ('revenda', models.CharField(max_length=200)),
                ('cliente', models.CharField(max_length=200)),
                ('cnpj_cpf', models.CharField(max_length=200)),
                ('codigo_erp', models.CharField(max_length=200)),
                ('comissao_over', models.CharField(max_length=200)),
                ('porcentagem_z6', models.CharField(max_length=200)),
                ('valor_total', models.FloatField()),
                ('observacao', models.CharField(max_length=200)),
                ('centros', models.CharField(max_length=200)),
                ('ordem', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=200)),
                ('dt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=200)),
                ('log', models.CharField(max_length=200)),
                ('data_hora', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoNfs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=200)),
                ('nf', models.CharField(max_length=200)),
                ('situacao', models.CharField(max_length=200)),
                ('data_emissao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoRemessas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=200)),
                ('remessa', models.CharField(max_length=200)),
            ],
        ),
    ]
