# Generated by Django 5.1.7 on 2025-04-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosFinaceirosClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiz_cnpj', models.CharField(max_length=200)),
                ('vencimento_limite', models.DateField()),
                ('valor_limite', models.FloatField()),
                ('valor_em_aberto', models.FloatField()),
                ('margem', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PedidosPendentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiz_cnpj', models.CharField(max_length=200)),
                ('pedido', models.CharField(max_length=200)),
                ('valor', models.FloatField()),
            ],
        ),
    ]
