# Generated by Django 5.1.7 on 2025-04-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dadosfinaceirosclientes_pedidospendentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosfinaceirosclientes',
            name='nfs_vencidas',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
    ]
