# Generated by Django 5.1.7 on 2025-04-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dadosfinaceirosclientes_nfs_vencidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosfinaceirosclientes',
            name='id',
        ),
        migrations.AlterField(
            model_name='dadosfinaceirosclientes',
            name='raiz_cnpj',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
