# Generated by Django 5.1.7 on 2025-04-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_dadosfinaceirosclientes_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosfinaceirosclientes',
            name='margem',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dadosfinaceirosclientes',
            name='valor_em_aberto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dadosfinaceirosclientes',
            name='valor_limite',
            field=models.CharField(max_length=200),
        ),
    ]
