# Generated by Django 5.1.7 on 2025-04-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_dadosfinaceirosclientes_margem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidospendentes',
            name='valor',
            field=models.CharField(max_length=200),
        ),
    ]
