# Generated by Django 5.1.7 on 2025-04-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_pedidospendentes_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosfinaceirosclientes',
            name='vencimento_limite',
            field=models.CharField(max_length=200),
        ),
    ]
