# Generated by Django 5.1.7 on 2025-04-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_dadosfinaceirosclientes_vencimento_limite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidospendentes',
            name='id',
        ),
        migrations.AlterField(
            model_name='pedidospendentes',
            name='pedido',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
