# Generated by Django 5.1.7 on 2025-04-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_pedidospendentes_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodados',
            name='valor_total',
            field=models.CharField(max_length=200),
        ),
    ]
