# Generated by Django 5.1.7 on 2025-04-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_pedidodados_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidodados',
            name='id',
        ),
        migrations.AlterField(
            model_name='pedidodados',
            name='pedido',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
