# Generated by Django 5.1.7 on 2025-04-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_pedidodados_id_alter_pedidodados_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('modulo', models.CharField(max_length=200)),
            ],
        ),
    ]
