# Generated by Django 5.1.7 on 2025-04-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auth',
            new_name='ModulesAuth',
        ),
    ]
