# Generated by Django 5.1.7 on 2025-04-11 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_auth_modulesauth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidodados',
            old_name='porcentagem_z6',
            new_name='porcentagem_comissao',
        ),
    ]
