# Generated by Django 5.1.7 on 2025-04-11 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_porcentagem_z6_pedidodados_porcentagem_comissao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidodados',
            old_name='comissao_over',
            new_name='over',
        ),
    ]
