# Generated by Django 5.1.7 on 2025-04-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_comissao_over_pedidodados_over'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=200)),
                ('centro', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=200)),
                ('valor', models.CharField(max_length=200)),
            ],
        ),
    ]
