# Generated by Django 5.1.7 on 2025-04-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_pedidoitens'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatabaseAuth',
        ),
    ]
