# Generated by Django 5.1.7 on 2025-04-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_tiposcanal_tiposcondicaopagamento_tiposdocumento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
    ]
