# Generated by Django 5.1.7 on 2025-04-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_tiposcentro_tiposdeposito'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
    ]
