# Generated by Django 5.1.7 on 2025-04-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_tiposgarantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposgarantia',
            name='valor',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
    ]
