# Generated by Django 5.1.7 on 2025-05-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_tiposgarantia_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(max_length=200)),
                ('organizacao', models.CharField(max_length=200)),
                ('canal', models.CharField(max_length=200)),
                ('escritorio', models.CharField(max_length=200)),
                ('equipe', models.CharField(max_length=200)),
                ('pedido_nome', models.CharField(max_length=200)),
                ('emissor', models.CharField(max_length=200)),
                ('recebedor', models.CharField(max_length=200)),
                ('forma_pagamento', models.CharField(max_length=200)),
                ('condicao_pagamento', models.CharField(max_length=200)),
                ('incoterm', models.CharField(max_length=200)),
                ('motivo', models.CharField(max_length=200)),
                ('expedicao', models.CharField(max_length=200)),
                ('dados_adicionais', models.CharField(max_length=200)),
                ('tabela', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DocsVendaComissionados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
                ('porcentagem', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DocsVendaItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=200)),
                ('quantidade', models.CharField(max_length=200)),
                ('valor_unitario', models.CharField(max_length=200)),
                ('centro', models.CharField(max_length=200)),
                ('deposito', models.CharField(max_length=200)),
                ('over', models.CharField(max_length=200)),
                ('garantia', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DocsVendaParceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
            ],
        ),
    ]
