# Generated by Django 5.1.7 on 2025-05-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_docsvenda_docsvendacomissionados_docsvendaitens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsvendacomissionados',
            name='id_referencia',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docsvendaitens',
            name='id_referencia',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docsvendaparceiros',
            name='id_referencia',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
    ]
