# Generated by Django 5.1.7 on 2025-05-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_docsvendacomissionados_id_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsvendaitens',
            name='valor_total',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
    ]
